---
name: Create PRs on each update
on:
  push:
    branches:
      - main

jobs:
  announce-update:
    name: 'Announce updates'
    runs-on: ubuntu-latest
    if: github.repository_owner == 'OpenSlides'
    env:
      EVENT_TYPE: meta-update
      PAYLOAD: '{"commit": "${{ github.sha }}"}'

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate access token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Send dispatch to autoupdate service
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: ${{ env.EVENT_TYPE }}
          repository: ${{ github.repository_owner }}/openslides-autoupdate-service
          token: ${{ steps.generate-token.outputs.token }}
          client-payload: ${{ env.PAYLOAD }}

      - name: Send dispatch to backend
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: ${{ env.EVENT_TYPE }}
          repository: ${{ github.repository_owner }}/openslides-backend
          token: ${{ steps.generate-token.outputs.token }}
          client-payload: ${{ env.PAYLOAD }}

      - name: Send dispatch to client
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: ${{ env.EVENT_TYPE }}
          repository: ${{ github.repository_owner }}/openslides-client
          token: ${{ steps.generate-token.outputs.token }}
          client-payload: ${{ env.PAYLOAD }}

      - name: Send dispatch to search service
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: ${{ env.EVENT_TYPE }}
          repository: ${{ github.repository_owner }}/openslides-search-service
          token: ${{ steps.generate-token.outputs.token }}
          client-payload: ${{ env.PAYLOAD }}
